CREATE TABLE coach
(
    id               UUID NOT NULL,
    user_id          UUID,
    training_type_id UUID,
    CONSTRAINT pk_coach PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE trainee
(
    id         UUID NOT NULL,
    user_id    UUID,
    birth_date date,
    address    VARCHAR(255),
    CONSTRAINT pk_trainee PRIMARY KEY (id)
);

CREATE TABLE trainee_coach
(
    id         UUID NOT NULL,
    trainee_id UUID,
    coach_id   UUID,
    CONSTRAINT pk_traineecoach PRIMARY KEY (id)
);

CREATE TABLE training
(
    id               UUID NOT NULL,
    trainee_id       UUID,
    coach_id         UUID,
    training_name    VARCHAR(255),
    training_type_id UUID,
    date             date,
    duration         INTEGER,
    CONSTRAINT pk_training PRIMARY KEY (id)
);

CREATE TABLE training_type
(
    id   UUID NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_trainingtype PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         UUID NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    phone      VARCHAR(255),
    email      VARCHAR(255),
    password   VARCHAR(255),
    is_active  BOOLEAN,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE users_roles
(
    user_id  UUID    NOT NULL,
    roles_id INTEGER NOT NULL
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE coach
    ADD CONSTRAINT FK_COACH_ON_TRAINING_TYPE FOREIGN KEY (training_type_id) REFERENCES training_type (id);

ALTER TABLE coach
    ADD CONSTRAINT FK_COACH_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE trainee_coach
    ADD CONSTRAINT FK_TRAINEECOACH_ON_COACH FOREIGN KEY (coach_id) REFERENCES coach (id);

ALTER TABLE trainee_coach
    ADD CONSTRAINT FK_TRAINEECOACH_ON_TRAINEE FOREIGN KEY (trainee_id) REFERENCES trainee (id);

ALTER TABLE trainee
    ADD CONSTRAINT FK_TRAINEE_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE training
    ADD CONSTRAINT FK_TRAINING_ON_COACH FOREIGN KEY (coach_id) REFERENCES coach (id);

ALTER TABLE training
    ADD CONSTRAINT FK_TRAINING_ON_TRAINEE FOREIGN KEY (trainee_id) REFERENCES trainee (id);

ALTER TABLE training
    ADD CONSTRAINT FK_TRAINING_ON_TRAINING_TYPE FOREIGN KEY (training_type_id) REFERENCES training_type (id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (roles_id) REFERENCES roles (id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id);


